### ISSUE TITLE
Not working with minitest 5

### ISSUE THREAD

**Issue by NicolasWebDev** [splattael/minitest-libnotify#2]
Gives the following error:
```
/home/sathors/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-growl-0.0.3/lib/minitest/growl_notify.rb:40:in `<top (required)>': undefined method `output' for Minitest::Unit:Class (NoMethodError)        
        from test/sri_test.rb:3:in `require'        
        from test/sri_test.rb:3:in `<main>'         
```

Related to torquebox/jruby-maven-plugins#74.

Seems that Minitest::Unit.output has been removed in minitest 5.

**Comment by jnbt** [comment]
I had the same issues with minitest-growl, https://github.com/jnbt/minitest-growl/commit/afa38e42cf3af9edb4b115b775c18d406cbd39c3

**Comment by splattael** [comment]
:+1: I will fix it next few days. Thanks!

**Comment by NicolasWebDev** [comment]
Thanks for your reactivity @splattael !
